# Generated by Django 4.1.13 on 2024-07-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="album_covers/"),
        ),
    ]
