# Generated by Django 4.1.13 on 2024-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/user_default_photo.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
