# Generated by Django 4.1.13 on 2024-07-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_album_cover_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="caption_strategy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
