# Generated by Django 4.1.13 on 2024-07-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_album_id_alter_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_of_creation',
            new_name='date_of_uploading',
        ),
    ]
